architecture:
    backbone: xlm-roberta-large
    dropout: 0.0
    embedding_size: 512
    intermediate_dropout: 0.0
    pool: '[CLS] token'
    pretrained: true
dataset:
    label_columns: label
    separator: ''
    text_column:
    - language
    - category
    - title
    - description
    train_dataframe: data/train_folded_v8_reverse.csv
environment:
    mixed_precision_training: true
    number_of_workers: 12
    seed: -1
experiment_name: fancy-pants-ff-v7
tokenizer:
    lowercase: false
    max_length: 64
    padding_quantile: 1.0
training:
    arcface_margin: 0.3
    arcface_margin_max: 0.0
    arcface_scale: 15.0
    batch_size: 256
    differential_learning_rate: 8.0e-05
    differential_learning_rate_layers:
    - backbone
    drop_last_batch: true
    epochs: 25
    learning_rate: 0.0005
    loss_function: ArcFace
    optimizer: AdamW
    schedule: Cosine
    warmup_epochs: 3
    weight_decay: 0.0
