architecture:
    backbone: xlm-roberta-large
    dropout: 0.0
    embedding_size: 512
    intermediate_dropout: 0.0
    pool: '[CLS] token'
    pretrained: true
dataset:
    label_columns: label
    separator: ''
    text_column:
    - language
    - category
    - title
    - breadcrumb
    - description
    - text
    train_dataframe: data/train_folded_v9.csv
environment:
    mixed_precision_training: true
    number_of_workers: 4
    seed: -1
experiment_name: flawless-flamingo.1.1.3-ff-v2
tokenizer:
    lowercase: false
    max_length: 128
    padding_quantile: 1.0
training:
    arcface_margin: 0.1
    arcface_margin_max: 0.0
    arcface_scale: 15.0
    batch_size: 196
    differential_learning_rate: 7.5e-05
    differential_learning_rate_layers:
    - backbone
    drop_last_batch: true
    epochs: 15
    learning_rate: 0.0005
    loss_function: ArcFace
    optimizer: AdamW
    schedule: Cosine
    warmup_epochs: 5
    weight_decay: 0.0
