architecture:
    backbone: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
    dropout: 0.0
    embedding_size: 512
    intermediate_dropout: 0.0
    pool: '[CLS] token'
    pretrained: true
dataset:
    label_columns: label
    separator: ''
    text_column:
    - language
    - category
    - title
    - description
    train_dataframe: data/train_folded_v7.csv
environment:
    mixed_precision_training: true
    number_of_workers: 4
    seed: -1
experiment_name: hopeful-flamingo.2.1-ff
tokenizer:
    lowercase: false
    max_length: 128
    padding_quantile: 1.0
training:
    arcface_margin: 0.5
    arcface_margin_max: 0.0
    arcface_scale: 15.0
    batch_size: 256
    differential_learning_rate: 0.0002
    differential_learning_rate_layers:
    - backbone
    drop_last_batch: true
    epochs: 30
    learning_rate: 0.001
    loss_function: ArcFaceLossAdaptiveMargin
    optimizer: AdamW
    schedule: Cosine
    warmup_epochs: 5
    weight_decay: 0.0
